all:
	gcc Pipes.c -o Pipes
	gcc 2_client.c -o 2_client
	gcc 2_server.c -o 2_server
	gcc 3_client.c -o 3_client
	gcc 3_server.c -o 3_server
	
clean:
	rm -rf Pipes
	rm -rf 2_client
	rm -rf 2_server
	rm -rf 3_client
	rm -rf 3_server

rebuild: clean all
